The latest version of Feren OS Browser Manager

diff --git a/usr/share/browser-manager/chrome/install b/usr/share/browser-manager/chrome/install
--- a/usr/share/browser-manager/chrome/install
+++ b/usr/share/browser-manager/chrome/install
@@ -1,40 +1,66 @@
 #!/bin/bash
 
+###############################
+#Check if program is installed#
+###############################
+dpkg -l google-chrome-stable |grep -q ^ii
 
+if [ $? -eq 0 ]; then
+         if [ -e "/usr/bin/google-chrome" ]; then
+                  zenity --info --title="Information" --text="Google Chrome is already installed" --no-wrap &
+                  exit 0
+         fi
+fi
 
 ################
 #Check for root#
 ################
-if [ ! $USERNAME = "root" ]; then
-    gksudo --description="Web Browser Manager" /usr/share/browser-manager/chrome/install
+if [ ! $(whoami) = "root" ]; then
+    if [ ! -f /tmp/chrome-tos.txt ]; then
+        lynx --dump https://www.google.com/chrome/browser/privacy/eula_text.html | awk 'NR>1' > /tmp/chrome-tos.txt
+        chmod 755 /tmp/chrome-tos.txt
+    fi
+    echo "The use of Google Chrome is governed by these terms and conditions, are you sure you want to install Chrome?
+    $(cat /tmp/chrome-tos.txt)" > /tmp/chrome-tos.txt
+    if [ -f /tmp/chrome-tos.txt ]; then
+        zenity --text-info --filename=/tmp/chrome-tos.txt --title="Continue?" --text  --checkbox="I read and accept the terms. I would like to install Google Chrome." --cancel-label="No" --ok-label="Yes" --icon-name="dialog-question"
+    else
+        ##########
+        #Question#
+        ##########
+        zenity --question --title="Continue?" --text "Are you sure you want to install Google Chrome?" --no-wrap
+    fi
+
+    if [ ! $? -eq 0 ]; then
+        exit
+    fi
+
+    pkexec "$0"
+    
+    if [ $? -eq 127 ]; then
+        exit 0
+    fi    
+    
+    ######################
+    #Double Check Package#
+    ######################
+    if [ -e "/usr/bin/google-chrome" ]; then
+            zenity --info --title="Installation Complete" --text="Google Chrome was successfully installed" --no-wrap &
+            exit 0
+    fi
+    #######
+    #Error#
+    #######
+    zenity  --error --text="Feren OS couldn't install Google Chrome successfully
+
+A log can be found at File System/tmp/chrome-install-log" --title="Error" --no-wrap &
     exit 0
-fi
-
-##########
-#Question#
-##########
-zenity --question --title="Continue?" --text "Are you sure you want to continue?"
-
-if [ ! $? -eq 0 ]; then
-           exit
-fi
-
-###############################
-#Check if program is installed#
-###############################
-dpkg --get-selections | grep -P -q "google-chrome-stable\t*install"
-
-if [ $? -eq 0 ]; then
-         if [ -e "/usr/bin/google-chrome" ]; then
-                  zenity --info --title="Information" --text="Google Chrome is already installed!"
-                  exit 0
-         fi
 fi
 
 ###################################
 #Check if program is not installed#
 ###################################
-dpkg --get-selections | grep -P -q "google-chrome-stable\t*install"
+dpkg -l google-chrome-stable |grep -q ^ii
 
 if [ ! $? -eq 0 ]; then
          if [ ! -e "/usr/bin/google-chrome" ]; then
@@ -42,28 +68,24 @@ if [ ! $? -eq 0 ]; then
 #################
 #Install program#
 #################
-                  apt-get update | zenity --progress --title="Installing..." --text="Updating package archive..." --pulsate --auto-close && apt-get -y install google-chrome-stable | zenity --progress --title="Installing..." --text="Downloading and Installing..." --pulsate --auto-close
+        #Log output
+        exec 1>/tmp/chrome-install-log 2>&1
+        
+                if [ ! -f /etc/apt/sources.list.d/google-chrome.list ]; then
+                    wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
+                    if [ ! $? -eq 0 ]; then
+                        exit 1
+                    fi
+                    echo -e "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
+                fi
+                apt-get update
+                apt-get -y install google-chrome-stable
          fi
-         ######################
-         #Double Check Package#
-         ######################
-         dpkg --get-selections | grep -P -q "google-chrome-stable\t*install"
-
-         if [ $? -eq 0 ]; then
-                  if [ -e "/usr/bin/google-chrome" ]; then
-                           zenity --info --title="Installation Complete" --text="Google Chrome installed successfully!"
-                           exit 0
-                  fi
-                  #######
-                  #Error#
-                  #######
-                  zenity  --error --text="An error occured." --title="Error"
-                  exit 0
-         fi
+         exit
 fi
 
 #######
 #Error#
 #######
-zenity  --error --text="An error occured." --title="Error"
+zenity  --error --text="An error occured while initiating the Google Chrome installation process" --title="Error" --no-wrap &
 exit 0
diff --git a/usr/share/browser-manager/chrome/uninstall b/usr/share/browser-manager/chrome/uninstall
--- a/usr/share/browser-manager/chrome/uninstall
+++ b/usr/share/browser-manager/chrome/uninstall
@@ -1,40 +1,57 @@
 #!/bin/bash
 
+###################################
+#Check if program is not installed#
+###################################
+dpkg -l google-chrome-stable |grep -q ^ii
 
+if [ ! $? -eq 0 ]; then
+         if [ ! -e "/usr/bin/google-chrome" ]; then
+                  zenity --info --title="Information" --text="Google Chrome is not installed" --no-wrap &
+                  exit 0
+         fi
+fi
 
 ################
 #Check for root#
 ################
-if [ ! $USERNAME = "root" ]; then
-    gksudo --description="Web Browser Manager" /usr/share/browser-manager/chrome/uninstall
-    exit 0
-fi
+if [ ! "$(whoami)" = "root" ]; then
+    zenity --question --title="Continue?" --text "Are you sure you want to remove Google Chrome?" --no-wrap
 
-##########
-#Question#
-##########
-zenity --question --title="Continue?" --text "Are you sure you want to continue?"
+    if [ ! $? -eq 0 ]; then
+            exit
+    fi
+    
+    pkexec "$0" $@
+    
+    if [ $? -eq 127 ]; then
+        exit 0
+    fi
+    
+    ######################
+    #Double Check Package#
+    ######################
+    dpkg --get-selections | grep -P -q "google-chrome-stable\t*install"
 
-if [ ! $? -eq 0 ]; then
-           exit
-fi
+    if [ ! $? -eq 0 ]; then
+            if [ ! -e "/usr/bin/google-chrome" ]; then
+                    zenity --info --title="Uninstalled Google Chrome" --text="Google Chrome was successfully removed" --no-wrap &
+                    exit 0
+            fi
+            #######
+            #Error#
+            #######
+            zenity  --error --text="Feren OS couldn't remove Google Chrome successfully
 
-###################################
-#Check if program is not installed#
-###################################
-dpkg --get-selections | grep -P -q "google-chrome-stable\t*install"
-
-if [ ! $? -eq 0 ]; then
-         if [ ! -e "/usr/bin/google-chrome" ]; then
-                  zenity --info --title="Information" --text="Google Chrome is not installed!"
-                  exit 0
-         fi
+A log can be found at File System/tmp/chrome-removal-log" --title="Error" --no-wrap &
+            exit 0
+    fi
 fi
 
 ###############################
 #Check if program is installed#
 ###############################
-dpkg --get-selections | grep -P -q "google-chrome-stable\t*install"
+dpkg -l google-chrome-stable |grep -q ^ii
 
 if [ $? -eq 0 ]; then
          if [ -e "/usr/bin/google-chrome" ]; then
@@ -42,28 +59,16 @@ if [ $? -eq 0 ]; then
 ###################
 #Uninstall program#
 ###################
-                  apt-get -y remove google-chrome-stable | zenity --progress --title="Uninstalling..." --text="Uninstalling..." --pulsate --auto-close
+        #Log output
+        exec 1>/tmp/chrome-removal-log 2>&1
+        
+                  apt-get -y remove google-chrome-stable
          fi
-         ######################
-         #Double Check Package#
-         ######################
-         dpkg --get-selections | grep -P -q "google-chrome-stable\t*install"
-
-         if [ ! $? -eq 0 ]; then
-                  if [ ! -e "/usr/bin/google-chrome" ]; then
-                           zenity --info --title="Uninstalled Google Chrome" --text="Google Chrome uninstalled successfully!"
-                           exit 0
-                  fi
-                  #######
-                  #Error#
-                  #######
-                  zenity  --error --text="An error occured." --title="Error"
-                  exit 0
-         fi
+         exit
 fi
 
 #######
 #Error#
 #######
-zenity  --error --text="An error occured." --title="Error"
+zenity  --error --text="An error occured while initiating the Google Chrome removal process" --title="Error" --no-wrap &
 exit 0
diff --git a/usr/share/browser-manager/firefox/install b/usr/share/browser-manager/firefox/install
--- a/usr/share/browser-manager/firefox/install
+++ b/usr/share/browser-manager/firefox/install
@@ -1,40 +1,57 @@
 #!/bin/bash
 
+###############################
+#Check if program is installed#
+###############################
+dpkg -l firefox |grep -q ^ii
+
+if [ $? -eq 0 ]; then
+         if [ -e "/usr/bin/firefox" ]; then
+                  zenity --info --title="Information" --text="Mozilla Firefox is already installed" --no-wrap &
+                  exit 0
+         fi
+fi
+
 
 
 ################
 #Check for root#
 ################
-if [ ! $USERNAME = "root" ]; then
-    gksudo --description="Web Browser Manager" /usr/share/browser-manager/firefox/install
-    exit 0
-fi
+if [ ! $(whoami) = "root" ]; then
+    zenity --question --title="Continue?" --text "The use of Mozilla Firefox is governed by the Terms found at
+https://www.mozilla.org/en-US/about/legal/terms/firefox/,
+are you sure you want to install Mozilla Firefox?" --no-wrap
 
-##########
-#Question#
-##########
-zenity --question --title="Continue?" --text "Are you sure you want to continue?"
-
-if [ ! $? -eq 0 ]; then
+    if [ ! $? -eq 0 ]; then
            exit
-fi
+    fi
 
-###############################
-#Check if program is installed#
-###############################
-dpkg --get-selections | grep -P -q "firefox\t*install"
+    pkexec "$0"
+    
+    if [ $? -eq 127 ]; then
+        exit 0
+    fi
+    
+    ######################
+    #Double Check Package#
+    ######################
+    if [ -e "/usr/bin/firefox" ]; then
+            zenity --info --title="Installation Complete" --text="Mozilla Firefox was successfully installed" --no-wrap &
+            exit 0
+    fi
+    #######
+    #Error#
+    #######
+    zenity  --error --text="Feren OS couldn't install Mozilla Firefox successfully
 
-if [ $? -eq 0 ]; then
-         if [ -e "/usr/bin/firefox" ]; then
-                  zenity --info --title="Information" --text="Firefox is already installed!"
-                  exit 0
-         fi
+A log can be found at File System/tmp/firefox-install-log" --title="Error" --no-wrap &
+    exit 0
 fi
 
 ###################################
 #Check if program is not installed#
 ###################################
-dpkg --get-selections | grep -P -q "firefox\t*install"
+dpkg -l firefox |grep -q ^ii
 
 if [ ! $? -eq 0 ]; then
          if [ ! -e "/usr/bin/firefox" ]; then
@@ -42,28 +59,17 @@ if [ ! $? -eq 0 ]; then
 #################
 #Install program#
 #################
-                  apt-get update | zenity --progress --title="Installing..." --text="Updating package archive..." --pulsate --auto-close && apt-get -y install firefox | zenity --progress --title="Installing..." --text="Downloading and Installing..." --pulsate --auto-close
+        #Log output
+        exec 1>/tmp/firefox-install-log 2>&1
+        
+                  apt-get update
+                  apt-get -y install firefox
          fi
-         ######################
-         #Double Check Package#
-         ######################
-         dpkg --get-selections | grep -P -q "firefox\t*install"
-
-         if [ $? -eq 0 ]; then
-                  if [ -e "/usr/bin/firefox" ]; then
-                           zenity --info --title="Installation Complete" --text="Firefox installed successfully!"
-                           exit 0
-                  fi
-                  #######
-                  #Error#
-                  #######
-                  zenity  --error --text="An error occured." --title="Error"
-                  exit 0
-         fi
+         exit
 fi
 
 #######
 #Error#
 #######
-zenity  --error --text="An error occured." --title="Error"
+zenity  --error --text="An error occured while initiating the Mozilla Firefox installation process." --title="Error" --no-wrap &
 exit 0
diff --git a/usr/share/browser-manager/firefox/uninstall b/usr/share/browser-manager/firefox/uninstall
--- a/usr/share/browser-manager/firefox/uninstall
+++ b/usr/share/browser-manager/firefox/uninstall
@@ -1,40 +1,57 @@
 #!/bin/bash
 
+###################################
+#Check if program is not installed#
+###################################
+dpkg -l firefox |grep -q ^ii
 
+if [ ! $? -eq 0 ]; then
+         if [ ! -e "/usr/bin/firefox" ]; then
+                  zenity --info --title="Information" --text="Mozilla Firefox is not installed" --no-wrap &
+                  exit 0
+         fi
+fi
 
 ################
 #Check for root#
 ################
-if [ ! $USERNAME = "root" ]; then
-    gksudo --description="Web Browser Manager" /usr/share/browser-manager/firefox/uninstall
-    exit 0
-fi
+if [ ! "$(whoami)" = "root" ]; then
+    zenity --question --title="Continue?" --text "Are you sure you want to remove Mozilla Firefox?" --no-wrap
 
-##########
-#Question#
-##########
-zenity --question --title="Continue?" --text "Are you sure you want to continue?"
+    if [ ! $? -eq 0 ]; then
+            exit
+    fi
+    
+    pkexec "$0" $@
+    
+    if [ $? -eq 127 ]; then
+        exit 0
+    fi
+    
+    ######################
+    #Double Check Package#
+    ######################
+    dpkg -l firefox |grep -q ^ii
 
-if [ ! $? -eq 0 ]; then
-           exit
-fi
+    if [ ! $? -eq 0 ]; then
+            if [ ! -e "/usr/bin/firefox" ]; then
+                    zenity --info --title="Uninstalled Mozilla Firefox" --text="Mozilla Firefox was successfully removed" --no-wrap &
+                    exit 0
+            fi
+            #######
+            #Error#
+            #######
+            zenity  --error --text="Feren OS couldn't remove Mozilla Firefox successfully
 
-###################################
-#Check if program is not installed#
-###################################
-dpkg --get-selections | grep -P -q "firefox\t*install"
-
-if [ ! $? -eq 0 ]; then
-         if [ ! -e "/usr/bin/firefox" ]; then
-                  zenity --info --title="Information" --text="Firefox is not installed!"
-                  exit 0
-         fi
+A log can be found at File System/tmp/firefox-removal-log" --title="Error" --no-wrap &
+            exit 0
+    fi
 fi
 
 ###############################
 #Check if program is installed#
 ###############################
-dpkg --get-selections | grep -P -q "firefox\t*install"
+dpkg -l firefox |grep -q ^ii
 
 if [ $? -eq 0 ]; then
          if [ -e "/usr/bin/firefox" ]; then
@@ -42,28 +59,16 @@ if [ $? -eq 0 ]; then
 ###################
 #Uninstall program#
 ###################
-                  apt-get -y remove firefox | zenity --progress --title="Uninstalling..." --text="Uninstalling..." --pulsate --auto-close
+        #Log output
+        exec 1>/tmp/firefox-removal-log 2>&1
+        
+                  apt-get -y remove firefox
          fi
-         ######################
-         #Double Check Package#
-         ######################
-         dpkg --get-selections | grep -P -q "firefox\t*install"
-
-         if [ ! $? -eq 0 ]; then
-                  if [ ! -e "/usr/bin/firefox" ]; then
-                           zenity --info --title="Uninstalled Firefox" --text="Firefox uninstalled successfully!"
-                           exit 0
-                  fi
-                  #######
-                  #Error#
-                  #######
-                  zenity  --error --text="An error occured." --title="Error"
-                  exit 0
-         fi
+         exit
 fi
 
 #######
 #Error#
 #######
-zenity  --error --text="An error occured." --title="Error"
+zenity  --error --text="An error occured while initiating the Mozilla Firefox removal process" --title="Error" --no-wrap &
 exit 0
diff --git a/usr/share/browser-manager/web/install b/usr/share/browser-manager/web/install
--- a/usr/share/browser-manager/web/install
+++ b/usr/share/browser-manager/web/install
@@ -1,40 +1,55 @@
 #!/bin/bash
 
+###############################
+#Check if program is installed#
+###############################
+dpkg -l epiphany-browser |grep -q ^ii
+
+if [ $? -eq 0 ]; then
+         if [ -e "/usr/bin/epiphany-browser" ]; then
+                  zenity --info --title="Information" --text="GNOME Web is already installed" --no-wrap &
+                  exit 0
+         fi
+fi
+
 
 
 ################
 #Check for root#
 ################
-if [ ! $USERNAME = "root" ]; then
-    gksudo --description="Web Browser Manager" /usr/share/browser-manager/web/install
-    exit 0
-fi
-
-##########
-#Question#
-##########
-zenity --question --title="Continue?" --text "Are you sure you want to continue?"
-
-if [ ! $? -eq 0 ]; then
+if [ ! $(whoami) = "root" ]; then
+    zenity --question --title="Continue?" --text "Are you sure you want to install GNOME Web?" --no-wrap
+    
+    if [ ! $? -eq 0 ]; then
            exit
-fi
+    fi
 
-###############################
-#Check if program is installed#
-###############################
-dpkg --get-selections | grep -P -q "epiphany-browser\t*install"
+    pkexec "$0"
+    
+    if [ $? -eq 127 ]; then
+        exit 0
+    fi
+    
+    ######################
+    #Double Check Package#
+    ######################
+    if [ -e "/usr/bin/epiphany-browser" ]; then
+            zenity --info --title="Installation Complete" --text="GNOME Web was successfully installed" --no-wrap &
+            exit 0
+    fi
+    #######
+    #Error#
+    #######
+    zenity  --error --text="Feren OS couldn't install GNOME Web successfully
 
-if [ $? -eq 0 ]; then
-         if [ -e "/usr/bin/epiphany-browser" ]; then
-                  zenity --info --title="Information" --text="Web is already installed!"
-                  exit 0
-         fi
+A log can be found at File System/tmp/epiphany-install-log" --title="Error" --no-wrap &
+    exit 0
 fi
 
 ###################################
 #Check if program is not installed#
 ###################################
-dpkg --get-selections | grep -P -q "epiphany-browser\t*install"
+dpkg -l epiphany-browser |grep -q ^ii
 
 if [ ! $? -eq 0 ]; then
          if [ ! -e "/usr/bin/epiphany-browser" ]; then
@@ -42,28 +57,17 @@ if [ ! $? -eq 0 ]; then
 #################
 #Install program#
 #################
-                  apt-get update | zenity --progress --title="Installing..." --text="Updating package archive..." --pulsate --auto-close && apt-get -y install epiphany-browser epiphany-browser-data | zenity --progress --title="Installing..." --text="Downloading and Installing..." --pulsate --auto-close
+        #Log output
+        exec 1>/tmp/epiphany-install-log 2>&1
+        
+                  apt-get update
+                  apt-get -y install epiphany-browser epiphany-browser-data
          fi
-         ######################
-         #Double Check Package#
-         ######################
-         dpkg --get-selections | grep -P -q "epiphany-browser\t*install"
-
-         if [ $? -eq 0 ]; then
-                  if [ -e "/usr/bin/epiphany-browser" ]; then
-                           zenity --info --title="Installation Complete" --text="Web installed successfully!"
-                           exit 0
-                  fi
-                  #######
-                  #Error#
-                  #######
-                  zenity  --error --text="An error occured." --title="Error"
-                  exit 0
-         fi
+         exit
 fi
 
 #######
 #Error#
 #######
-zenity  --error --text="An error occured." --title="Error"
+zenity  --error --text="An error occured while initiating the GNOME Web installation process" --title="Error" --no-wrap &
 exit 0
diff --git a/usr/share/browser-manager/web/uninstall b/usr/share/browser-manager/web/uninstall
--- a/usr/share/browser-manager/web/uninstall
+++ b/usr/share/browser-manager/web/uninstall
@@ -1,59 +1,74 @@
 #!/bin/bash
 
-
-
-################
-#Check for root#
-################
-if [ ! $USERNAME = "root" ]; then
-    gksudo --description="Web Browser Manager" /usr/share/browser-manager/web/uninstall
-    exit 0
-fi
-
-##########
-#Question#
-##########
-zenity --question --title="Continue?" --text "Are you sure you want to continue?"
-
-if [ ! $? -eq 0 ]; then
-           exit
-fi
-
 ###################################
 #Check if program is not installed#
 ###################################
 dpkg --get-selections | grep -P -q "epiphany-browser\t*install"
 
-if [ $? -ne 0 ]; then
+if [ ! $? -eq 0 ]; then
          if [ ! -e "/usr/bin/epiphany-browser" ]; then
-                  zenity --info --title="Information" --text="Web is not installed!"
+                  zenity --info --title="Information" --text="GNOME Web is not installed" --no-wrap &
                   exit 0
          fi
 fi
 
+################
+#Check for root#
+################
+if [ ! "$(whoami)" = "root" ]; then
+    zenity --question --title="Continue?" --text "Are you sure you want to remove GNOME Web?" --no-wrap
+
+    if [ ! $? -eq 0 ]; then
+            exit
+    fi
+    
+    pkexec "$0" $@
+    
+    if [ $? -eq 127 ]; then
+        exit 0
+    fi
+    
+    ######################
+    #Double Check Package#
+    ######################
+    dpkg --get-selections | grep -P -q "epiphany-browser\t*install"
+
+    if [ ! $? -eq 0 ]; then
+            if [ ! -e "/usr/bin/epiphany-browser" ]; then
+                    zenity --info --title="Uninstalled GNOME Web" --text="GNOME Web was successfully removed" --no-wrap &
+                    exit 0
+            fi
+            #######
+            #Error#
+            #######
+            zenity  --error --text="Feren OS couldn't remove GNOME Web successfully
+
+A log can be found at File System/tmp/epiphany-removal-log" --title="Error" --no-wrap &
+            exit 0
+    fi
+fi
+
+###############################
+#Check if program is installed#
+###############################
+dpkg --get-selections | grep -P -q "epiphany-browser\t*install"
+
+if [ $? -eq 0 ]; then
+         if [ -e "/usr/bin/epiphany-browser" ]; then
+
 ###################
 #Uninstall program#
 ###################
-                  apt-get -y remove epiphany-browser epiphany-browser-data | zenity --progress --title="Uninstalling..." --text="Uninstalling..." --pulsate --auto-close
-         ######################
-         #Double Check Package#
-         ######################
-         dpkg --get-selections | grep -P -q "epiphany-browser\t*install"
-
-         if [ $? -ne 0 ]; then
-                  if [ ! -e "/usr/bin/epiphany-browser" ]; then
-                           zenity --info --title="Uninstalled Web" --text="Web uninstalled successfully!"
-                           exit 0
-                  fi
-                  #######
-                  #Error#
-                  #######
-                  zenity  --error --text="An error occured." --title="Error"
-                  exit 0
+        #Log output
+        exec 1>/tmp/epiphany-removal-log 2>&1
+        
+                  apt-get -y remove epiphany-browser
          fi
+         exit
+fi
 
 #######
 #Error#
 #######
-zenity  --error --text="An error occured." --title="Error"
+zenity  --error --text="An error occured while initiating the GNOME Web removal process." --title="Error" --no-wrap &
 exit 0
